# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dream Weddings By Shahida
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Wedding planner, events services and decor rentals in Cleveland
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:title/
url: "https://ivanchromjak.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: ivanchromjak

facebook_username: dreamweddingsbyshahida
instagram_username: dreamweddingsbyshahida
instagram_accesstoken: 2350456011.9b52aa4.3d57c6b8a1e747cba2a36419a59695c7

logo: "/assets/img/logo-dark.svg"
social:
  name: Ivan Chromjak
  links:
    - https://twitter.com/ivanchromjak
    - https://www.linkedin.com/in/ivan-chromjak-2946b043/
    - https://github.com/ivanchromjak

twitter_username: ivanchromjak
github_username:  ivanchromjak
linkedin_username: ivanchromjak

# google_analytics:
footer_text: Made by <a href="https://ivanchromjak.com/">Ivan</a> somewhere on the planet earth.
# paginate: 2

# Build settings
markdown: kramdown
highlighter: rouge

# theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style: compressed
